$(function() {

today = new Date();
den=today.getDate();
mesic=(today.getMonth()+1);



if (mesic==1) {
if (den==01) var svateka = ("Nový rok");
if (den==02) var svateka = ("Karina");
if (den==03) var svateka = ("Radmila");
if (den==04) var svateka = ("Diana");
if (den==05) var svateka = ("Dalimil");
if (den==06) var svateka = ("Tři králové");
if (den==07) var svateka = ("Vilma");
if (den==08) var svateka = ("Èestmír");
if (den==09) var svateka = ("Vladan");
if (den==10) var svateka = ("Břetislav");
if (den==11) var svateka = ("Bohdana");
if (den==12) var svateka = ("Pravoslav");
if (den==13) var svateka = ("Edita");
if (den==14) var svateka = ("Radovan");
if (den==15) var svateka = ("Alice");
if (den==16) var svateka = ("Ctirad");
if (den==17) var svateka = ("Drahoslav");
if (den==18) var svateka = ("Vladislav");
if (den==19) var svateka = ("Doubravka");
if (den==20) var svateka = ("Ilona");
if (den==21) var svateka = ("Bìla");
if (den==22) var svateka = ("Slavomír");
if (den==23) var svateka = ("Zdenìk");
if (den==24) var svateka = ("Milena");
if (den==25) var svateka = ("Miloš");
if (den==26) var svateka = ("Zora");
if (den==27) var svateka = ("Ingrid");
if (den==28) var svateka = ("Otýlie");
if (den==29) var svateka = ("Zdislava");
if (den==30) var svateka = ("Robin");
if (den==31) var svateka = ("Marika");
}
if (mesic==2) {
if (den==01) var svateka = ("Hynek");
if (den==02) var svateka = ("Nela");
if (den==03) var svateka = ("Blažej");
if (den==04) var svateka = ("Jarmila");
if (den==05) var svateka = ("Dobromila");
if (den==06) var svateka = ("Vanda");
if (den==07) var svateka = ("Veronika");
if (den==08) var svateka = ("Milada");
if (den==09) var svateka = ("Apolena");
if (den==10) var svateka = ("Mojmír");
if (den==11) var svateka = ("Božena");
if (den==12) var svateka = ("Slavìna");
if (den==13) var svateka = ("Vìnceslav");
if (den==14) var svateka = ("Valentýn");
if (den==15) var svateka = ("Jiřina");
if (den==16) var svateka = ("Ljuba");
if (den==17) var svateka = ("Miloslava");
if (den==18) var svateka = ("Gizela");
if (den==19) var svateka = ("Patrik");
if (den==20) var svateka = ("Oldřich");
if (den==21) var svateka = ("Lenka");
if (den==22) var svateka = ("Petr");
if (den==23) var svateka = ("Svatopluk");
if (den==24) var svateka = ("Matìj");
if (den==25) var svateka = ("Liliana");
if (den==26) var svateka = ("Dorota");
if (den==27) var svateka = ("Alexandr");
if (den==28) var svateka = ("Lumír");
if (den==29) var svateka = ("");
}
if (mesic==3) {
if (den==01) var svateka = ("Bedřich");
if (den==02) var svateka = ("Anežka");
if (den==03) var svateka = ("Kamil");
if (den==04) var svateka = ("Stela");
if (den==05) var svateka = ("Kazimir");
if (den==06) var svateka = ("Miroslav");
if (den==07) var svateka = ("Tomáš");
if (den==08) var svateka = ("Gabriela");
if (den==09) var svateka = ("Františka");
if (den==10) var svateka = ("Viktorie");
if (den==11) var svateka = ("Andìla");
if (den==12) var svateka = ("řehoř");
if (den==13) var svateka = ("Rùžena");
if (den==14) var svateka = ("Rùt a matylda");
if (den==15) var svateka = ("Ida");
if (den==16) var svateka = ("Elena a herbert");
if (den==17) var svateka = ("Vlastimil");
if (den==18) var svateka = ("Eduard");
if (den==19) var svateka = ("Josef");
if (den==20) var svateka = ("Svìtlana");
if (den==21) var svateka = ("Radek");
if (den==22) var svateka = ("Leona");
if (den==23) var svateka = ("Ivona");
if (den==24) var svateka = ("Gabriel");
if (den==25) var svateka = ("Marian");
if (den==26) var svateka = ("Emanuel");
if (den==27) var svateka = ("Dita");
if (den==28) var svateka = ("Soòa");
if (den==29) var svateka = ("Taána");
if (den==30) var svateka = ("Arnošt");
if (den==31) var svateka = ("Kvido");
}
if (mesic==4) {
if (den==01) var svateka = ("Hugo");
if (den==02) var svateka = ("Erika");
if (den==03) var svateka = ("Richard");
if (den==04) var svateka = ("Ivana");
if (den==05) var svateka = ("Miroslava");
if (den==06) var svateka = ("Vendula");
if (den==07) var svateka = ("Heřman a Hermína");
if (den==08) var svateka = ("Ema");
if (den==09) var svateka = ("Dušan");
if (den==10) var svateka = ("Darja");
if (den==11) var svateka = ("Izabela");
if (den==12) var svateka = ("Julius");
if (den==13) var svateka = ("Aleš");
if (den==14) var svateka = ("Vincenc");
if (den==15) var svateka = ("Anastázie");
if (den==16) var svateka = ("Irena");
if (den==17) var svateka = ("Rudolf");
if (den==18) var svateka = ("Valérie");
if (den==19) var svateka = ("Rostislav");
if (den==20) var svateka = ("Marcela");
if (den==21) var svateka = ("Alexandra");
if (den==22) var svateka = ("Evženie");
if (den==23) var svateka = ("Vojtìch");
if (den==24) var svateka = ("Jiří");
if (den==25) var svateka = ("Marek");
if (den==26) var svateka = ("Oto");
if (den==27) var svateka = ("Jaroslav");
if (den==28) var svateka = ("Vlastislav");
if (den==29) var svateka = ("Robert");
if (den==30) var svateka = ("Blahoslav");
}
if (mesic==5) {
if (den==01) var svateka = (" ");
if (den==02) var svateka = ("Zikmund");
if (den==03) var svateka = ("Alexej");
if (den==04) var svateka = ("Kvìtoslav");
if (den==05) var svateka = ("Klaudie");
if (den==06) var svateka = ("Radoslav");
if (den==07) var svateka = ("Stanislav");
if (den==08) var svateka = (" ");
if (den==09) var svateka = ("Ctibor");
if (den==10) var svateka = ("Blažena");
if (den==11) var svateka = ("Svatava");
if (den==12) var svateka = ("Pankrác");
if (den==13) var svateka = ("Servác");
if (den==14) var svateka = ("Bonifác");
if (den==15) var svateka = ("Žofie");
if (den==16) var svateka = ("Přemysl");
if (den==17) var svateka = ("Aneta");
if (den==18) var svateka = ("Nataša");
if (den==19) var svateka = ("Ivo");
if (den==20) var svateka = ("Zbyšek");
if (den==21) var svateka = ("Monika");
if (den==22) var svateka = ("Emil");
if (den==23) var svateka = ("Vladimír");
if (den==24) var svateka = ("Jana");
if (den==25) var svateka = ("Viola");
if (den==26) var svateka = ("Filip");
if (den==27) var svateka = ("Valdemar");
if (den==28) var svateka = ("Vilém");
if (den==29) var svateka = ("Maxmilián");
if (den==30) var svateka = ("Ferdinand");
if (den==31) var svateka = ("Kamila");
}
if (mesic==6) {
if (den==01) var svateka = ("Laura");
if (den==02) var svateka = ("Jarmil");
if (den==03) var svateka = ("Tamara");
if (den==04) var svateka = ("Dalibor");
if (den==05) var svateka = ("Dobroslav");
if (den==06) var svateka = ("Norbert");
if (den==07) var svateka = ("Iveta a Slavoj");
if (den==08) var svateka = ("Medard");
if (den==09) var svateka = ("Stanislava");
if (den==10) var svateka = ("Gita");
if (den==11) var svateka = ("Bruno");
if (den==12) var svateka = ("Antonie");
if (den==13) var svateka = ("Antonín");
if (den==14) var svateka = ("Roland");
if (den==15) var svateka = ("Vít");
if (den==16) var svateka = ("Zbynìk");
if (den==17) var svateka = ("Adolf");
if (den==18) var svateka = ("Milan");
if (den==19) var svateka = ("Leoš");
if (den==20) var svateka = ("Kvìta");
if (den==21) var svateka = ("Alois");
if (den==22) var svateka = ("Pavla");
if (den==23) var svateka = ("Zdeòka");
if (den==24) var svateka = ("Jan");
if (den==25) var svateka = ("Ivan");
if (den==26) var svateka = ("Adriana");
if (den==27) var svateka = ("Ladislav");
if (den==28) var svateka = ("Lubomír");
if (den==29) var svateka = ("Petr a Pavel");
if (den==30) var svateka = ("Šárka");
}
if (mesic==7) {
if (den==01) var svateka = ("Jaroslava");
if (den==02) var svateka = ("Patricie");
if (den==03) var svateka = ("Radomír");
if (den==04) var svateka = ("Prokop");
if (den==05) var svateka = (" ");
if (den==06) var svateka = (" ");
if (den==07) var svateka = ("Bohuslava");
if (den==08) var svateka = ("Nora");
if (den==09) var svateka = ("Drahoslava");
if (den==10) var svateka = ("Libuše a Amálie");
if (den==11) var svateka = ("Olga");
if (den==12) var svateka = ("Bořek");
if (den==13) var svateka = ("Markéta");
if (den==14) var svateka = ("Karolína");
if (den==15) var svateka = ("Jindřich");
if (den==16) var svateka = ("Luboš");
if (den==17) var svateka = ("Martina");
if (den==18) var svateka = ("Drahomíra");
if (den==19) var svateka = ("Èenìk");
if (den==20) var svateka = ("Ilja");
if (den==21) var svateka = ("Vítìzslav");
if (den==22) var svateka = ("Magdaléna");
if (den==23) var svateka = ("Libor");
if (den==24) var svateka = ("Kristýna");
if (den==25) var svateka = ("Jakub");
if (den==26) var svateka = ("Anna");
if (den==27) var svateka = ("Vìroslav");
if (den==28) var svateka = ("Viktor");
if (den==29) var svateka = ("Marta");
if (den==30) var svateka = ("Bořivoj");
if (den==31) var svateka = ("Ignác");
}
if (mesic==8) {
if (den==01) var svateka = ("Oskar");
if (den==02) var svateka = ("Gustav");
if (den==03) var svateka = ("Miluše");
if (den==04) var svateka = ("Dominik");
if (den==05) var svateka = ("Kristian");
if (den==06) var svateka = ("Oldřiška");
if (den==07) var svateka = ("Lada");
if (den==08) var svateka = ("Sobìslav");
if (den==09) var svateka = ("Roman");
if (den==10) var svateka = ("Vavřinec");
if (den==11) var svateka = ("Zuzana");
if (den==12) var svateka = ("Klára");
if (den==13) var svateka = ("Alena");
if (den==14) var svateka = ("Alan");
if (den==15) var svateka = ("Hana");
if (den==16) var svateka = ("Jáchym");
if (den==17) var svateka = ("Petra");
if (den==18) var svateka = ("Helena");
if (den==19) var svateka = ("Ludvík");
if (den==20) var svateka = ("Bernard");
if (den==21) var svateka = ("Johana");
if (den==22) var svateka = ("Bohuslav");
if (den==23) var svateka = ("Sandra");
if (den==24) var svateka = ("Bartolomìj");
if (den==25) var svateka = ("Radim");
if (den==26) var svateka = ("Ludìk");
if (den==27) var svateka = ("Otakar");
if (den==28) var svateka = ("Augustýn");
if (den==29) var svateka = ("Evelína");
if (den==30) var svateka = ("Vladìna");
if (den==31) var svateka = ("Pavlína");
}
if (mesic==9) {
if (den==01) var svateka = ("Linda a Samuel");
if (den==02) var svateka = ("Adéla");
if (den==03) var svateka = ("Bronislav");
if (den==04) var svateka = ("Jindřiška");
if (den==05) var svateka = ("Boris");
if (den==06) var svateka = ("Boleslav");
if (den==07) var svateka = ("Regína");
if (den==08) var svateka = ("Mariana");
if (den==09) var svateka = ("Daniela");
if (den==10) var svateka = ("Irma");
if (den==11) var svateka = ("Denisa");
if (den==12) var svateka = ("Marie");
if (den==13) var svateka = ("Lubor");
if (den==14) var svateka = ("Radka");
if (den==15) var svateka = ("Jolana");
if (den==16) var svateka = ("Ludmila");
if (den==17) var svateka = ("Nadìžda");
if (den==18) var svateka = ("Kryštof");
if (den==19) var svateka = ("Zita");
if (den==20) var svateka = ("Oleg");
if (den==21) var svateka = ("Matouš");
if (den==22) var svateka = ("Darina");
if (den==23) var svateka = ("Berta");
if (den==24) var svateka = ("Jaromír");
if (den==25) var svateka = ("Zlata");
if (den==26) var svateka = ("Andrea");
if (den==27) var svateka = ("Jonáš");
if (den==28) var svateka = ("Václav");
if (den==29) var svateka = ("Michal");
if (den==30) var svateka = ("Jeroným");

}
if (mesic==10) {
if (den==01) var svateka = ("Igor");
if (den==02) var svateka = ("Olivie a Oliver");
if (den==03) var svateka = ("Bohumil");
if (den==04) var svateka = ("František");
if (den==05) var svateka = ("Eliška");
if (den==06) var svateka = ("Hanuš");
if (den==07) var svateka = ("Justýna");
if (den==08) var svateka = ("Vìra");
if (den==09) var svateka = ("Štefan a Sára");
if (den==10) var svateka = ("Marina");
if (den==11) var svateka = ("Andrej");
if (den==12) var svateka = ("Marcel");
if (den==13) var svateka = ("Renáta");
if (den==14) var svateka = ("Agáta");
if (den==15) var svateka = ("Tereza");
if (den==16) var svateka = ("Havel");
if (den==17) var svateka = ("Hedvika");
if (den==18) var svateka = ("Lukáš");
if (den==19) var svateka = ("Michaela");
if (den==20) var svateka = ("Vendelín");
if (den==21) var svateka = ("Brigita");
if (den==22) var svateka = ("Sabina");
if (den==23) var svateka = ("Teodor");
if (den==24) var svateka = ("Nina");
if (den==25) var svateka = ("Beáta");
if (den==26) var svateka = ("Erik");
if (den==27) var svateka = ("Šarlota a Zoe");
if (den==28) var svateka = (" ");
if (den==29) var svateka = ("Silvie");
if (den==30) var svateka = ("Tadeáš");
if (den==31) var svateka = ("Štìpánka");
}
if (mesic==11) {
if (den==01) var svateka = ("Felix");
if (den==02) var svateka = (" ");
if (den==03) var svateka = ("Hubert");
if (den==04) var svateka = ("Karel");
if (den==05) var svateka = ("Miriam");
if (den==06) var svateka = ("Libìna");
if (den==07) var svateka = ("Saskie");
if (den==08) var svateka = ("Bohumír");
if (den==09) var svateka = ("Bohdan");
if (den==10) var svateka = ("Evžen");
if (den==11) var svateka = ("Martin");
if (den==12) var svateka = ("Benedikt");
if (den==13) var svateka = ("Tibor");
if (den==14) var svateka = ("Sáva");
if (den==15) var svateka = ("Leopold");
if (den==16) var svateka = ("Otmar");
if (den==17) var svateka = ("Mahulena");
if (den==18) var svateka = ("Romana");
if (den==19) var svateka = ("Alžbìta");
if (den==20) var svateka = ("Nikola");
if (den==21) var svateka = ("Albert");
if (den==22) var svateka = ("Cecílie");
if (den==23) var svateka = ("Klement");
if (den==24) var svateka = ("Emílie");
if (den==25) var svateka = ("Kateřina");
if (den==26) var svateka = ("Artur");
if (den==27) var svateka = ("Xenie");
if (den==28) var svateka = ("René");
if (den==29) var svateka = ("Zina");
if (den==30) var svateka = ("Ondřej");
}
if (mesic==12) {
if (den==01) var svateka = ("Iva");
if (den==02) var svateka = ("Blanka");
if (den==03) var svateka = ("Svatoslav");
if (den==04) var svateka = ("Barbora");
if (den==05) var svateka = ("Jitka");
if (den==06) var svateka = ("Mikuláš");
if (den==07) var svateka = ("Ambrož a Benjamín");
if (den==08) var svateka = ("Kvìtoslava");
if (den==09) var svateka = ("Vratislav");
if (den==10) var svateka = ("Julie");
if (den==11) var svateka = ("Dana");
if (den==12) var svateka = ("Simona");
if (den==13) var svateka = ("Lucie");
if (den==14) var svateka = ("Lýdie");
if (den==15) var svateka = ("Radana a Radan");
if (den==16) var svateka = ("Albína");
if (den==17) var svateka = ("Daniel");
if (den==18) var svateka = ("Miloslav");
if (den==19) var svateka = ("Ester");
if (den==20) var svateka = ("Dagmar");
if (den==21) var svateka = ("Natálie");
if (den==22) var svateka = ("Šimon");
if (den==23) var svateka = ("Vlasta");
if (den==24) var svateka = ("Adam a Eva");
if (den==25) var svateka = (" ");
if (den==26) var svateka = ("Štìpán");
if (den==27) var svateka = ("Žaneta");
if (den==28) var svateka = ("Bohumila");
if (den==29) var svateka = ("Judita");
if (den==30) var svateka = ("David");
if (den==31) var svateka = ("Silvestr");
}

$("#svateka").html(svateka);   

});










$(function() {

todayb = new Date();
denb=todayb.getDate();
mesicb=(todayb.getMonth()+1);



if (mesicb==1) {
if (denb==01) var svatekb = ("Karina");
if (denb==02) var svatekb = ("Radmila");
if (denb==03) var svatekb = ("Diana");
if (denb==04) var svatekb = ("Dalimil");
if (denb==05) var svatekb = ("Tři králové");
if (denb==06) var svatekb = ("Vilma");
if (denb==07) var svatekb = ("Èestmír");
if (denb==08) var svatekb = ("Vladan");
if (denb==09) var svatekb = ("Břetislav");
if (denb==10) var svatekb = ("Bohdana");
if (denb==11) var svatekb = ("Pravoslav");
if (denb==12) var svatekb = ("Edita");
if (denb==13) var svatekb = ("Radovan");
if (denb==14) var svatekb = ("Alice");
if (denb==15) var svatekb = ("Ctirad");
if (denb==16) var svatekb = ("Drahoslav");
if (denb==17) var svatekb = ("Vladislav");
if (denb==18) var svatekb = ("Doubravka");
if (denb==19) var svatekb = ("Ilona");
if (denb==20) var svatekb = ("Bìla");
if (denb==21) var svatekb = ("Slavomír");
if (denb==22) var svatekb = ("Zdenbìk");
if (denb==23) var svatekb = ("Milena");
if (denb==24) var svatekb = ("Miloš");
if (denb==25) var svatekb = ("Zora");
if (denb==26) var svatekb = ("Ingrid");
if (denb==27) var svatekb = ("Otýlie");
if (denb==28) var svatekb = ("Zdislava");
if (denb==29) var svatekb = ("Robin");
if (denb==30) var svatekb = ("Marika");
if (denb==31) var svatekb = ("Hynek");
}
if (mesicb==2) {
if (denb==01) var svatekb = ("Nela");
if (denb==02) var svatekb = ("Blažej");
if (denb==03) var svatekb = ("Jarmila");
if (denb==04) var svatekb = ("Dobromila");
if (denb==05) var svatekb = ("Vanda");
if (denb==06) var svatekb = ("Veronika");
if (denb==07) var svatekb = ("Milada");
if (denb==08) var svatekb = ("Apolena");
if (denb==09) var svatekb = ("Mojmír");
if (denb==10) var svatekb = ("Božena");
if (denb==11) var svatekb = ("Slavìna");
if (denb==12) var svatekb = ("Vìnceslav");
if (denb==13) var svatekb = ("Valentýn");
if (denb==14) var svatekb = ("Jiřina");
if (denb==15) var svatekb = ("Ljuba");
if (denb==16) var svatekb = ("Miloslava");
if (denb==17) var svatekb = ("Gizela");
if (denb==18) var svatekb = ("Patrik");
if (denb==19) var svatekb = ("Oldřich");
if (denb==20) var svatekb = ("Lenka");
if (denb==21) var svatekb = ("Petr");
if (denb==22) var svatekb = ("Svatopluk");
if (denb==23) var svatekb = ("Matìj");
if (denb==24) var svatekb = ("Liliana");
if (denb==25) var svatekb = ("Dorota");
if (denb==26) var svatekb = ("Alexandr");
if (denb==27) var svatekb = ("Lumír");
if (denb==28) var svatekb = ("Bedřich");
}
if (mesicb==3) {

if (denb==01) var svatekb = ("Anežka");
if (denb==02) var svatekb = ("Kamil");
if (denb==03) var svatekb = ("Stela");
if (denb==04) var svatekb = ("Kazimir");
if (denb==05) var svatekb = ("Miroslav");
if (denb==06) var svatekb = ("Tomáš");
if (denb==07) var svatekb = ("Gabriela");
if (denb==08) var svatekb = ("Františka");
if (denb==09) var svatekb = ("Viktorie");
if (denb==10) var svatekb = ("Andìla");
if (denb==11) var svatekb = ("řehoř");
if (denb==12) var svatekb = ("Rùžena");
if (denb==13) var svatekb = ("Rùt a matylda");
if (denb==14) var svatekb = ("Ida");
if (denb==15) var svatekb = ("Elena a herbert");
if (denb==16) var svatekb = ("Vlastimil");
if (denb==17) var svatekb = ("Eduard");
if (denb==18) var svatekb = ("Josef");
if (denb==19) var svatekb = ("Svìtlana");
if (denb==20) var svatekb = ("Radek");
if (denb==21) var svatekb = ("Leona");
if (denb==22) var svatekb = ("Ivona");
if (denb==23) var svatekb = ("Gabriel");
if (denb==24) var svatekb = ("Marian");
if (denb==25) var svatekb = ("Emanuel");
if (denb==26) var svatekb = ("Dita");
if (denb==27) var svatekb = ("Soòa");
if (denb==28) var svatekb = ("Taána");
if (denb==29) var svatekb = ("Arnošt");
if (denb==30) var svatekb = ("Kvido");
if (denb==31) var svatekb = ("Hugo");
}
if (mesicb==4) {
if (denb==01) var svatekb = ("Erika");
if (denb==02) var svatekb = ("Richard");
if (denb==03) var svatekb = ("Ivana");
if (denb==04) var svatekb = ("Miroslava");
if (denb==05) var svatekb = ("Vendula");
if (denb==06) var svatekb = ("Heřman a Hermína");
if (denb==07) var svatekb = ("Ema");
if (denb==08) var svatekb = ("Dušan");
if (denb==09) var svatekb = ("Darja");
if (denb==10) var svatekb = ("Izabela");
if (denb==11) var svatekb = ("Julius");
if (denb==12) var svatekb = ("Aleš");
if (denb==13) var svatekb = ("Vincenc");
if (denb==14) var svatekb = ("Anastázie");
if (denb==15) var svatekb = ("Irena");
if (denb==16) var svatekb = ("Rudolf");
if (denb==17) var svatekb = ("Valérie");
if (denb==18) var svatekb = ("Rostislav");
if (denb==19) var svatekb = ("Marcela");
if (denb==20) var svatekb = ("Alexandra");
if (denb==21) var svatekb = ("Evženie");
if (denb==22) var svatekb = ("Vojtìch");
if (denb==23) var svatekb = ("Jiří");
if (denb==24) var svatekb = ("Marek");
if (denb==25) var svatekb = ("Oto");
if (denb==26) var svatekb = ("Jaroslav");
if (denb==27) var svatekb = ("Vlastislav");
if (denb==28) var svatekb = ("Robert");
if (denb==29) var svatekb = ("Blahoslav");
if (denb==30) var svatekb = (" ");
}
if (mesicb==5) {

if (denb==01) var svatekb = ("Zikmund");
if (denb==02) var svatekb = ("Alexej");
if (denb==03) var svatekb = ("Kvìtoslav");
if (denb==04) var svatekb = ("Klaudie");
if (denb==05) var svatekb = ("Radoslav");
if (denb==06) var svatekb = ("Stanislav");
if (denb==07) var svatekb = (" ");
if (denb==08) var svatekb = ("Ctibor");
if (denb==09) var svatekb = ("Blažena");
if (denb==10) var svatekb = ("Svatava");
if (denb==11) var svatekb = ("Pankrác");
if (denb==12) var svatekb = ("Servác");
if (denb==13) var svatekb = ("Bonifác");
if (denb==14) var svatekb = ("Žofie");
if (denb==15) var svatekb = ("Přemysl");
if (denb==16) var svatekb = ("Aneta");
if (denb==17) var svatekb = ("Nataša");
if (denb==18) var svatekb = ("Ivo");
if (denb==19) var svatekb = ("Zbyšek");
if (denb==20) var svatekb = ("Monika");
if (denb==21) var svatekb = ("Emil");
if (denb==22) var svatekb = ("Vladimír");
if (denb==23) var svatekb = ("Jana");
if (denb==24) var svatekb = ("Viola");
if (denb==25) var svatekb = ("Filip");
if (denb==26) var svatekb = ("Valdemar");
if (denb==27) var svatekb = ("Vilém");
if (denb==28) var svatekb = ("Maxmilián");
if (denb==29) var svatekb = ("Ferdinand");
if (denb==30) var svatekb = ("Kamila");
if (denb==31) var svatekb = ("Laura");
}
if (mesicb==6) {
if (denb==01) var svatekb = ("Jarmil");
if (denb==02) var svatekb = ("Tamara");
if (denb==03) var svatekb = ("Dalibor");
if (denb==04) var svatekb = ("Dobroslav");
if (denb==05) var svatekb = ("Norbert");
if (denb==06) var svatekb = ("Iveta a Slavoj");
if (denb==07) var svatekb = ("Medard");
if (denb==08) var svatekb = ("Stanislava");
if (denb==09) var svatekb = ("Gita");
if (denb==10) var svatekb = ("Bruno");
if (denb==11) var svatekb = ("Antonie");
if (denb==12) var svatekb = ("Antonín");
if (denb==13) var svatekb = ("Roland");
if (denb==14) var svatekb = ("Vít");
if (denb==15) var svatekb = ("Zbynìk");
if (denb==16) var svatekb = ("Adolf");
if (denb==17) var svatekb = ("Milan");
if (denb==18) var svatekb = ("Leoš");
if (denb==19) var svatekb = ("Kvìta");
if (denb==20) var svatekb = ("Alois");
if (denb==21) var svatekb = ("Pavla");
if (denb==22) var svatekb = ("Zdeòka");
if (denb==23) var svatekb = ("Jan");
if (denb==24) var svatekb = ("Ivan");
if (denb==25) var svatekb = ("Adriana");
if (denb==26) var svatekb = ("Ladislav");
if (denb==27) var svatekb = ("Lubomír");
if (denb==28) var svatekb = ("Petr a Pavel");
if (denb==29) var svatekb = ("Šárka");
if (denb==30) var svatekb = ("Jaroslava");
}
if (mesicb==7) {
if (denb==01) var svatekb = ("Patricie");
if (denb==02) var svatekb = ("Radomír");
if (denb==03) var svatekb = ("Prokop");
if (denb==04) var svatekb = (" ");
if (denb==05) var svatekb = (" ");
if (denb==06) var svatekb = ("Bohuslava");
if (denb==07) var svatekb = ("Nora");
if (denb==08) var svatekb = ("Drahoslava");
if (denb==09) var svatekb = ("Libuše a Amálie");
if (denb==10) var svatekb = ("Olga");
if (denb==11) var svatekb = ("Bořek");
if (denb==12) var svatekb = ("Markéta");
if (denb==13) var svatekb = ("Karolína");
if (denb==14) var svatekb = ("Jindřich");
if (denb==15) var svatekb = ("Luboš");
if (denb==16) var svatekb = ("Martina");
if (denb==17) var svatekb = ("Drahomíra");
if (denb==18) var svatekb = ("Èenìk");
if (denb==19) var svatekb = ("Ilja");
if (denb==20) var svatekb = ("Vítìzslav");
if (denb==21) var svatekb = ("Magdaléna");
if (denb==22) var svatekb = ("Libor");
if (denb==23) var svatekb = ("Kristýna");
if (denb==24) var svatekb = ("Jakub");
if (denb==25) var svatekb = ("Anna");
if (denb==26) var svatekb = ("Vìroslav");
if (denb==27) var svatekb = ("Viktor");
if (denb==28) var svatekb = ("Marta");
if (denb==29) var svatekb = ("Bořivoj");
if (denb==30) var svatekb = ("Ignác");
if (denb==31) var svatekb = ("Oskar");
}
if (mesicb==8) {
if (denb==01) var svatekb = ("Gustav");
if (denb==02) var svatekb = ("Miluše");
if (denb==03) var svatekb = ("Dominik");
if (denb==04) var svatekb = ("Kristian");
if (denb==05) var svatekb = ("Oldřiška");
if (denb==06) var svatekb = ("Lada");
if (denb==07) var svatekb = ("Sobìslav");
if (denb==08) var svatekb = ("Roman");
if (denb==09) var svatekb = ("Vavřinec");
if (denb==10) var svatekb = ("Zuzana");
if (denb==11) var svatekb = ("Klára");
if (denb==12) var svatekb = ("Alena");
if (denb==13) var svatekb = ("Alan");
if (denb==14) var svatekb = ("Hana");
if (denb==15) var svatekb = ("Jáchym");
if (denb==16) var svatekb = ("Petra");
if (denb==17) var svatekb = ("Helena");
if (denb==18) var svatekb = ("Ludvík");
if (denb==19) var svatekb = ("Bernard");
if (denb==20) var svatekb = ("Johana");
if (denb==21) var svatekb = ("Bohuslav");
if (denb==22) var svatekb = ("Sandra");
if (denb==23) var svatekb = ("Bartolomìj");
if (denb==24) var svatekb = ("Radim");
if (denb==25) var svatekb = ("Ludìk");
if (denb==26) var svatekb = ("Otakar");
if (denb==27) var svatekb = ("Augustýn");
if (denb==28) var svatekb = ("Evelína");
if (denb==29) var svatekb = ("Vladìna");
if (denb==30) var svatekb = ("Pavlína");
if (denb==31) var svatekb = ("Linda a Samuel");
}
if (mesicb==9) {
if (denb==01) var svatekb = ("Adéla");
if (denb==02) var svatekb = ("Bronislav");
if (denb==03) var svatekb = ("Jindřiška");
if (denb==04) var svatekb = ("Boris");
if (denb==05) var svatekb = ("Boleslav");
if (denb==06) var svatekb = ("Regína");
if (denb==07) var svatekb = ("Mariana");
if (denb==08) var svatekb = ("Daniela");
if (denb==09) var svatekb = ("Irma");
if (denb==10) var svatekb = ("denbisa");
if (denb==11) var svatekb = ("Marie");
if (denb==12) var svatekb = ("Lubor");
if (denb==13) var svatekb = ("Radka");
if (denb==14) var svatekb = ("Jolana");
if (denb==15) var svatekb = ("Ludmila");
if (denb==16) var svatekb = ("Nadìžda");
if (denb==17) var svatekb = ("Kryštof");
if (denb==18) var svatekb = ("Zita");
if (denb==19) var svatekb = ("Oleg");
if (denb==20) var svatekb = ("Matouš");
if (denb==21) var svatekb = ("Darina");
if (denb==22) var svatekb = ("Berta");
if (denb==23) var svatekb = ("Jaromír");
if (denb==24) var svatekb = ("Zlata");
if (denb==25) var svatekb = ("Andrea");
if (denb==26) var svatekb = ("Jonáš");
if (denb==27) var svatekb = ("Václav");
if (denb==28) var svatekb = ("Michal");
if (denb==29) var svatekb = ("Jeroným");
if (denb==30) var svatekb = ("Igor");
}
if (mesicb==10) {
if (denb==01) var svatekb = ("Olivie a Oliver");
if (denb==02) var svatekb = ("Bohumil");
if (denb==03) var svatekb = ("František");
if (denb==04) var svatekb = ("Eliška");
if (denb==05) var svatekb = ("Hanuš");
if (denb==06) var svatekb = ("Justýna");
if (denb==07) var svatekb = ("Vìra");
if (denb==08) var svatekb = ("Štefan a Sára");
if (denb==09) var svatekb = ("Marina");
if (denb==10) var svatekb = ("Andrej");
if (denb==11) var svatekb = ("Marcel");
if (denb==12) var svatekb = ("Renáta");
if (denb==13) var svatekb = ("Agáta");
if (denb==14) var svatekb = ("Tereza");
if (denb==15) var svatekb = ("Havel");
if (denb==16) var svatekb = ("Hedvika");
if (denb==17) var svatekb = ("Lukáš");
if (denb==18) var svatekb = ("Michaela");
if (denb==19) var svatekb = ("Vendelín");
if (denb==20) var svatekb = ("Brigita");
if (denb==21) var svatekb = ("Sabina");
if (denb==22) var svatekb = ("Teodor");
if (denb==23) var svatekb = ("Nina");
if (denb==24) var svatekb = ("Beáta");
if (denb==25) var svatekb = ("Erik");
if (denb==26) var svatekb = ("Šarlota a Zoe");
if (denb==27) var svatekb = (" ");
if (denb==28) var svatekb = ("Silvie");
if (denb==29) var svatekb = ("Tadeáš");
if (denb==30) var svatekb = ("Štìpánka");
if (denb==31) var svatekb = ("Felix");
}
if (mesicb==11) {
if (denb==01) var svatekb = (" ");
if (denb==02) var svatekb = ("Hubert");
if (denb==03) var svatekb = ("Karel");
if (denb==04) var svatekb = ("Miriam");
if (denb==05) var svatekb = ("Libìna");
if (denb==06) var svatekb = ("Saskie");
if (denb==07) var svatekb = ("Bohumír");
if (denb==08) var svatekb = ("Bohdan");
if (denb==09) var svatekb = ("Evžen");
if (denb==10) var svatekb = ("Martin");
if (denb==11) var svatekb = ("Benedikt");
if (denb==12) var svatekb = ("Tibor");
if (denb==13) var svatekb = ("Sáva");
if (denb==14) var svatekb = ("Leopold");
if (denb==15) var svatekb = ("Otmar");
if (denb==16) var svatekb = ("Mahulena");
if (denb==17) var svatekb = ("Romana");
if (denb==18) var svatekb = ("Alžbìta");
if (denb==19) var svatekb = ("Nikola");
if (denb==20) var svatekb = ("Albert");
if (denb==21) var svatekb = ("Cecílie");
if (denb==22) var svatekb = ("Klement");
if (denb==23) var svatekb = ("Emílie");
if (denb==24) var svatekb = ("Kateřina");
if (denb==25) var svatekb = ("Artur");
if (denb==26) var svatekb = ("Xenie");
if (denb==27) var svatekb = ("René");
if (denb==28) var svatekb = ("Zina");
if (denb==29) var svatekb = ("Ondřej");
if (denb==30) var svatekb = ("Iva");
}
if (mesicb==12) {
if (denb==01) var svatekb = ("Blanka");
if (denb==02) var svatekb = ("Svatoslav");
if (denb==03) var svatekb = ("Barbora");
if (denb==04) var svatekb = ("Jitka");
if (denb==05) var svatekb = ("Mikuláš");
if (denb==06) var svatekb = ("Ambrož a Benjamín");
if (denb==07) var svatekb = ("Kvìtoslava");
if (denb==08) var svatekb = ("Vratislav");
if (denb==09) var svatekb = ("Julie");
if (denb==10) var svatekb = ("Dana");
if (denb==11) var svatekb = ("Simona");
if (denb==12) var svatekb = ("Lucie");
if (denb==13) var svatekb = ("Lýdie");
if (denb==14) var svatekb = ("Radana a Radan");
if (denb==15) var svatekb = ("Albína");
if (denb==16) var svatekb = ("Daniel");
if (denb==17) var svatekb = ("Miloslav");
if (denb==18) var svatekb = ("Ester");
if (denb==19) var svatekb = ("Dagmar");
if (denb==20) var svatekb = ("Natálie");
if (denb==21) var svatekb = ("Šimon");
if (denb==22) var svatekb = ("Vlasta");
if (denb==23) var svatekb = ("Adam a Eva");
if (denb==24) var svatekb = (" ");
if (denb==25) var svatekb = ("Štìpán");
if (denb==26) var svatekb = ("Žaneta");
if (denb==27) var svatekb = ("Bohumila");
if (denb==28) var svatekb = ("Judita");
if (denb==29) var svatekb = ("David");
if (denb==30) var svatekb = ("Silvestr");
if (denb==31) var svateka = ("Nový rok");
}

$("#svatekb").html(svatekb);   

});